# bin2h.ps1 - embed compiled shader blobs (.cso / .rs) into a C header.
# Symbol names: fg_<basename>_<ext> and fg_<basename>_<ext>_len
param(
    [Parameter(Mandatory=$true)][string]$InputDir,
    [Parameter(Mandatory=$true)][string]$Output
)
$ErrorActionPreference = "Stop"

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* generated by tools/bin2h.ps1 - do not edit */")
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("")

$files = Get-ChildItem -Path $InputDir -File | Where-Object { $_.Extension -in ".cso", ".rs" } | Sort-Object Name
if (-not $files) { throw "bin2h: no .cso/.rs files found in $InputDir" }

foreach ($f in $files) {
    $bytes = [System.IO.File]::ReadAllBytes($f.FullName)
    $name  = "fg_" + $f.BaseName + "_" + $f.Extension.TrimStart('.')
    [void]$sb.AppendLine("static const unsigned char $name[] = {")
    for ($i = 0; $i -lt $bytes.Length; $i += 32) {
        $end   = [Math]::Min($i + 31, $bytes.Length - 1)
        $chunk = $bytes[$i..$end] | ForEach-Object { $_.ToString() }
        [void]$sb.AppendLine("    " + ($chunk -join ",") + ",")
    }
    [void]$sb.AppendLine("};")
    [void]$sb.AppendLine("static const unsigned int " + $name + "_len = " + $bytes.Length + ";")
    [void]$sb.AppendLine("")
}

[System.IO.File]::WriteAllText($Output, $sb.ToString())
Write-Host ("bin2h: wrote {0} ({1} blobs)" -f $Output, $files.Count)
